name: gamma_smart_pagination
description: Flutter package for infinite scrolling pagination, which supports pull down to refresh and pull up to load more.
version: 0.0.2
repository: https://github.com/GammaTechMK/gamma_smart_pagination

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
